FROM node:18.17.1-slim AS base

# Set environment variables
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enable corepack
RUN corepack enable

# Set the working directory
WORKDIR /app

# Copy your application code into the container
COPY . /app

# Install development dependencies and run the development server
CMD pnpm install --frozen-lockfile && pnpm dev

# Expose port 8000 for the development server
EXPOSE 8000
